---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - sentinel.io
  resources:
  - remediationplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sentinel.io
  resources:
  - remediationplans/finalizers
  verbs:
  - update
- apiGroups:
  - sentinel.io
  resources:
  - remediationplans/status
  verbs:
  - get
  - patch
  - update
